use test;

CREATE TABLE TBL_SCHOOL_LUNCH (
  PUBLIC_ORGANIZATION_CD CHAR(6) NOT NULL COMMENT '全国地方公共団体コード',
  ID CHAR(10) NOT NULL COMMENT 'ID',
  PREFECTURE_NAME VARCHAR(3) NOT NULL COMMENT '都道府県名',
  CITY_NAME VARCHAR(3) NOT NULL COMMENT '市区町村名',
  COURSE_NAME CHAR(1) NOT NULL COMMENT 'コース名',
  SCHOOL_NAME VARCHAR(20) NOT NULL COMMENT '学校名',
  MENU_DATE DATE NOT NULL COMMENT '献立日',
  MENU_NO INT NOT NULL COMMENT '献立番号',
  DISH_NAME VARCHAR(100) COMMENT '料理名',
  ITEM_NO INT NOT NULL COMMENT '明細番号',
  FOOD_CATEGORY VARCHAR(100) NOT NULL COMMENT '食品区分',
  FOOD_NAME VARCHAR(100) NOT NULL COMMENT '食品名',
  CREATED_BY VARCHAR(100) NOT NULL COMMENT '作成者',
  CREATED_AT DATETIME NOT NULL COMMENT '作成日時' DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(100) COMMENT '更新者',
  UPDATED_AT DATETIME COMMENT '更新日時' DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(ID)
) ENGINE = InnoDB, COMMENT '給食献立管理テーブル';
