version: "3"

services:
  mysql:
    container_name: test-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      LANG: C.UTF-8
      LANGUAGE: ja_JP
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./config/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  flyway:
    container_name: test-flyway
    image: boxfuse/flyway:5.1.4
    depends_on:
      - mysql
    volumes:
      - ./config/flyway/conf:/flyway/conf
      - ./config/flyway/migration:/flyway/sql
    entrypoint: >
      /bin/sh -c "
      until (/flyway/flyway clean) do echo 'waiting ...' & sleep 1; done;
      /flyway/flyway migrate;
      exit $$?;
      "
  cloud-storage:
    container_name: test-cloud-storage
    image: fsouza/fake-gcs-server:1.43.0
    tty: true
    ports:
      - "4443:4443"
    volumes:
      - ./config/gcp/cloud-storage/data:/data/test
      - ./config/gcp/cloud-storage/storage:/storage
    command: -scheme http -public-host ${URL:-localhost}:4443

volumes:
  database:
    driver: local
